services:
  server:
    depends_on:
      - db
    env_file:
      - .env
    build: .
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app

  db:
    image: postgres:16.1-alpine
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
