name: run tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: chatbot

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.0
      - name: Create env file
        run: |
          touch .env
          echo TEST_POSTGRES_PORT=5432 >> .env
          echo TELEGRAM_TOKEN=irrelevant_for_tests >> .env
          cat .env

      - name: Migrate database
        run: go run cmd/migratedb/main.go -testdb

      - name: Run tests
        run: go test -v ./...
        env:
          TEST_POSTGRES_PORT: 5432